Večina kode je nared za Code Review
edinsabic/C pull request #15
Opened 2022-03-30 01:49 UTC by edinsabic

Igrica na splošno dela, nisem pa preveč testiral

2022-03-30 07:07 UTC, urosjarc requested changes
V World strukturi imaš preveč informacij (glej komentar) pri prejšnji igri sem to spregledal vendar zdaj bo pa treba stvar zrihtati kot se spodobi.

2022-03-30 12:18 UTC, edinsabic commented on 003_four_in_line_oop/src/domain/World.h
>      Zeton zetoni[WORLD_ST_ZETONOV];
V tem primeru sem spremenljivko aktiven `spremenil `v `porabljen`. Tukaj mislim da je smiselno ohraniti ta variable, saj priredim porabljenost žetona v `true`, ko ga vržem v ploščo. 
(Spremenil sem tudi, da je namesto `int`-a (ki je bil tukaj vedno 0 ali 1) sedaj `bool`, ki je `true `če je `Zeton ``porabljen `(spuščen v ploščo)

2022-03-30 12:44 UTC, edinsabic commented on 003_four_in_line_oop/src/domain/World.h
> +int world_check_diagonal_1(int dvaDTabela[WORLD_ST_VRSTIC][WORLD_ST_STOLPCEV], int one);
Tukaj sem včeraj poskusil na ta način, saj vem da je tako pravilnejše, da namesto tabele na začetku kot parameter pass-am samo stukturo `World` (od sedaj `Plosca`), vendar sem dobil error `**** stack smashing detected *** Aborted*`. Sem potem raje samo pustil tako kot je bilo, sedaj pa ko sem spremenil, stvar dela tako kot mora :)

Popravil sem tudi, da ne pass-am`plosca_is_win` funkciji cifre, ampak samo `Plosca`.

2022-03-30 12:53 UTC, edinsabic commented on 003_four_in_line_oop/src/domain/World.h
> +int world_check_diagonal_1(int dvaDTabela[WORLD_ST_VRSTIC][WORLD_ST_STOLPCEV], int one);
Ko poskušam na začetek privatnih funkcij (tistih 4 za preverjanje V/H/D1/D2) prependati `_` , torej takole `_plosca_check_diagonal_2` me CLion opozori: Decleration uses identifier, which is reserved in the global namespace. Sem raje dodal 3 `_` na koncu in dodal komentar v `Plosca.h` fajlu, da so to privatne funkcije. Če bi bilo bolje kako drugače, povej, bom popravil.

2022-03-30 15:36 UTC, urosjarc commented
Pazi, Prepend pomeni da ima private previx _ pomeni da ima eno črt pred ime funkcije... Se pravi
_plosca_check_vertical

2022-03-30 20:10 UTC, urosjarc requested changes
Nekaj stvari še nisi popravil iz prejšnjega review-a (prosim dobro si prvega oglej).

Samo daj res ščisti strukturo Ploščo ne potrebuješ toliko stvari notri met.

2022-03-30 20:10 UTC, urosjarc commented on 003_four_in_line_oop/src/domain/Plosca.h
> +bool plosca_check_diagonal_2___(Plosca* plosca, int num);
Prepend pomeni da je podcrtaj pred imenom _plosca_check_diagonal_2 pa uporabljaj samo eno crto ker dve crti sta rezervirani za sistemske private elemente.

2022-03-30 20:10 UTC, urosjarc commented on 003_four_in_line_oop/src/domain/Plosca.h
> +    int counterjiStolpcev[PLOSCA_ST_STOLPCEV];
Plošča naj ima samo
    int height;
    int width;
    Zeton zetoni[PLOSCA_ST_ZETONOV];
    bool active;

2022-03-30 20:10 UTC, urosjarc commented on 003_four_in_line_oop/src/domain/Plosca.h
> +    int counterjiStolpcev[PLOSCA_ST_STOLPCEV];
To pomeni da bo potrebno logiko v funkcijah kjer uporabljaš te stvari na novo napisati.

2022-03-30 20:12 UTC, urosjarc commented
OOOO lol, zdaj vidim kako github skriva moje review-je !!!!!!!!!!!!! Baraba!!!!!!!!!! Ti bom še enkrat tukaj napisal kar se je skrilo in kar nisi verjetno videl ko si delal popravke...

2022-03-30 20:15 UTC, urosjarc commented
Opa oprosti nisem videl tvojih komentarjev na mojih review-jih za kar se ti opravičujem, se moram tudi jaz navaditi na github flow.
Ti bom na tvoje odgovore pisal stvari.

2022-03-30 20:21 UTC, urosjarc commented on 003_four_in_line_oop/src/domain/World.h
> +int world_check_diagonal_1(int dvaDTabela[WORLD_ST_VRSTIC][WORLD_ST_STOLPCEV], int one);
To opozorilo lahko spregledaš saj bi en underscore moral delati, drugače lahko narediva tako da prependaš z p_ ime funkcije če ti clion teži.

2022-03-30 20:23 UTC, urosjarc commented on 003_four_in_line_oop/src/domain/World.h
> +    int dvaDTabela[WORLD_ST_VRSTIC][WORLD_ST_STOLPCEV];
Ok lej za to igro lahko pustiva tako kot je, da boš imel miren spanec pa bova šla k naslednji igri :)
Samo pri naslednji se pa res drži DDD-ja da bodo strukture čiste brez pomožnih stvari ki ti olajšajo programiranje.

2022-03-30 20:27 UTC, urosjarc commented on 003_four_in_line_oop/src/domain/World.h
> +int world_check_diagonal_1(int dvaDTabela[WORLD_ST_VRSTIC][WORLD_ST_STOLPCEV], int one);
Glede **** stack smashing detected *** Aborted* pa se to ne bi smelo dogajati če uporabljaš strukturo pravilno. :(
Za to igro lahko spregledava to pa boš pri naslednji popravil.

2022-03-30 20:27 UTC, urosjarc commented on 003_four_in_line_oop/src/domain/World.h
>      Zeton zetoni[WORLD_ST_ZETONOV];
Se strinjam.

2022-03-30 20:29 UTC, urosjarc commented
Ok lej preveri če vse dela tako kot mora potem pa kratek video, jaz bom pa mergal potem branch notri. Aja pa video naredi tudi za 002 element.

2022-03-30 20:39 UTC, urosjarc commented
Pa še nekaj sem opazil ne ti resolvat review-ja ker če mi resolvaš pa potem pošlješ email jaz tega emala ne bom dobil in je velika verjetnost da ti ne bom odgovoril!!! Poleg tega samo tisti ki ustvari review lahko potem resolva review.

2022-03-30 21:23 UTC, edinsabic commented
Sem prebral vse, se strinjam z vsem. Jutri zgodaj vstajam in sem na faxu cel dan, tako da bom jutri, ko bom imel čas odgovoriti na vsak reply posebaj to tudi naredil in zrihtal kokr se to igrico da do konca zrihtat. Do večera sem tam, tako da oba videa objavim jutri proti večeru.

2022-03-31 07:53 UTC, edinsabic commented on 003_four_in_line_oop/src/domain/World.h
> +    int dvaDTabela[WORLD_ST_VRSTIC][WORLD_ST_STOLPCEV];
Popolnoma razumem kaj misliš. Ta način pisanja sem uporabil pri tisti prvi verziji štiri v vrsto, ko še nisem razmišljal o strukturah, ampak samo o tem, da bo delalo. Ta način sem uporabil tudi pri tej. Stvar sedaj lepo dela, je pa brezveze izgubljat čas na tej igri, da bi jo na novo napisal. Tako da, se strinjam da greva naprej in pa bom pri naslednji igri upošteval, kar sva se tukaj naučila. In tega je kar precej :)

2022-03-31 07:55 UTC, edinsabic commented on 003_four_in_line_oop/src/domain/World.h
> +int world_check_diagonal_1(int dvaDTabela[WORLD_ST_VRSTIC][WORLD_ST_STOLPCEV], int one);
Sem prepend-al `p_` namesto `_`, da ne bo CLion jokal. 
Kar se pa stack smashing-a tiče. Vem, da se ne bi smelo dogajat. Najslabše je to, da kokr se spomnim sem stvar naredil na isti način kot prej, le da sedaj dela prej pa ni :( Verjetno sem kaj ornk zajebal, ampak sem pogruntal kako se pass-a sturkutre kot parameter, tako da mislim, da se ni treba sekirat.

2022-03-31 07:55 UTC, edinsabic commented on 003_four_in_line_oop/src/domain/World.c
> +void world_popolnjenost_stolpcev(World* world, int* tabela, int stolpecCounter, int vrstica) {
Odstranjeno.

2022-03-31 07:55 UTC, edinsabic commented on 003_four_in_line_oop/src/domain/World.c
> +int world_check_vertical(int dvaDTabela[WORLD_ST_VRSTIC][WORLD_ST_STOLPCEV], int one) {
Popravljeno, tudi na vseh delih projekta.

2022-03-31 07:55 UTC, edinsabic commented on 003_four_in_line_oop/src/domain/World.h
>      Zeton zetoni[WORLD_ST_ZETONOV];
🤝

2022-03-31 07:56 UTC, edinsabic commented on 003_four_in_line_oop/src/domain/utils.h
> +//
Popravljeno.

2022-03-31 08:01 UTC, edinsabic commented
Evo Uroš, sem popravil, kar se je popraviti dalo, in stvari tudi commit-al. Res je da je dosti indijansko, a mislim, da je sedaj as ready as it's ever going to be, tako da najbolje da greva kar naprej in ne izgubljava časa za brezveze.
Oprosti, ker sem sam resolval stvari, nisem niti pomislil, da ne bi smel. Sem jih sedaj, ko sem na vsak tvoj odgovor napisal nekaj, tudi unresolval, pa lahko ti zaključiš. Mislim, da sva se dokaj dobro navadila na GitHub, tako da od zdaj bi morala nemoteno delati naprej. Tudi kar se commit-anja, merga-anja in PR-ov tiče, mislim, da sem dobro dojel kako se stvari streže, tako da stvari ratajo od sedaj samo še elegantnejše.

Videa za obe igrici bom posnel danes zvečer, ko pridem domov, pa lahko merge-aš Pull Request. 

Car si, hvala ti :D !

2022-03-31 20:15 UTC, edinsabic commented
https://www.youtube.com/watch?v=Txu9RWTOhLY

2022-03-31 20:30 UTC, merged